### ISSUE TITLE
Compatible issue

### ISSUE THREAD

**Issue by yiming330** [yiming330/pqi-connect#1]
之前日本測試Connect 301發現到在Sony & Samsung 手機Android系統版本4.4.2, PQI Connect+無法使用
GALAXY S5 Smart Phone SC-04F 4.4.2 Cannot use "PQI Connect+" 
XPERIA ZL2 Smart Phone SOL25 4.4.2 Cannot use "PQI Connect+"

**Comment by yiming330** [comment]
請協助申請Connect的測試機兩台, 上次申請air系列時忘了提醒, 再麻煩你了.

**Comment by wuboy0307** [comment]
就目前觀察並使用 hTC M8測試 https://github.com/yiming330/pqi-connect/issues/2
目前connect+ 由於 android 4.4的修改，應該在4.4以上的版本皆不可使用，需修改程式中存取資料夾位置。

**Comment by yiming330** [comment]
此問題會針對4.4更新一版app一併解決. 預計release for testing - 9/11/2014

**Comment by wuboy0307** [comment]
此問題已做程式修改，將connect+ 更新可判讀4.4的路徑，並且在使用者於外部SD卡進行新增、刪除、更名等操作時，提示「由於android 4.4.2的規範，此動作無法於外部SD操作」的訊息。

目前需等待拿到公司上架使用的key方可更新程式。

**Comment by yiming330** [comment]
Issue fixed. Version 1.1.0 was released on 10/17/2014.
