### ISSUE TITLE
Connect+ App cannot auto run in Connect 301.

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-connect#3]
Connect+ App cannot auto run when Connect 301 plug-in, Connect 201/302 can auto run when plug-in.

**Comment by yiming330** [comment]
Ernest, please test if we can reproduce the issue.

**Comment by wuboy0307** [comment]
301未被定義在device_filter當中 以至於無法被偵測到

加入以下 vendor id定義後已可auto run
<usb-device vendor-id="5118" product-id="21760" />

**Comment by PQI-APP** [comment]
所以Connect + App會改版發行到網站嗎?

**Comment by wuboy0307** [comment]
Connect+ 本來就因應 4.4.2的問題需要改版，此問題可一併修正。

**Comment by PQI-APP** [comment]
請問預計完成的日期?

**Comment by yiming330** [comment]
目前已經完成開發. 我們這邊有用HTC M8做測試沒有問題. apk檔案會email給pqi同仁幫忙再測測看.

**Comment by yiming330** [comment]
Issue fixed. Version 1.1.0 was released on 10/17/2014.
